# fly.toml app configuration file generated for caveinvaders on 2023-07-10T10:07:44-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "caveinvaders"
primary_region = "sea"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
